Created LocalizationTest
Xceptance/neodymium-showcase pull request #10
Opened 2020-04-01 15:51 UTC by georgkunze

Created initial localization test.
#9

2020-04-02 09:28 UTC, occupant23 commented on config/localization.yaml
> +
use german locale 'de'

2020-04-02 11:10 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/localization/LocalizationTest.java
> +
change locale by manipulating the Neodymium property
`Neodymium.configuration().setProperty("neodymium.locale", "de");`

2020-04-02 11:13 UTC, occupant23 requested changes

2020-04-02 11:13 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/localization/LocalizationTest.java
> +        new Title().validateTitle(Neodymium.localizedText("homepage.title", "de"));
if locale is change the second parameter is not needed

2020-04-02 11:13 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/localization/LocalizationTest.java
> +        headLine.shouldHave(text(Neodymium.localizedText("homepage.headline", "de")));
if locale is change the second parameter is not needed

2020-04-02 11:13 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/localization/LocalizationTest.java
> +    }
add another localization item under "german" and demonstrate the specific call for a locale, add the same element for the english part above.

2020-06-04 07:18 UTC, ckeiner requested changes

2020-06-04 07:18 UTC, ckeiner commented on src/test/java/showcase/neodymium/tests/localization/LocalizationTest.java
> +        //from a specific locale.
```suggestion
        //Here the call to localizedText has another locale as second parameter to get
        //a specific String from that specific locale.
```

IMO, this sounds more concise.

2020-06-05 06:45 UTC, ckeiner reviewed
I will approve of these changes once occupant23's unresolved comment is completed.

2020-06-05 07:06 UTC, georgkunze commented
@ckeiner i added a check for the subtitle for the english site.

2020-06-05 08:18 UTC, ckeiner approved these changes

2020-06-05 09:51 UTC, merged