Slider showcase
Xceptance/neodymium-showcase pull request #21
Opened 2020-05-14 09:51 UTC by jseng92

2020-05-20 07:29 UTC, oomelianchuk approved these changes

2020-05-22 10:46 UTC, ckeiner requested changes

2020-05-22 10:46 UTC, ckeiner commented on src/test/java/showcase/neodymium/tests/slider/SliderTest.java
> +        Selenide.open("https://demos.telerik.com/kendo-ui/slider/index");
Make the URL a member of the class since you use it in every method.

2020-05-22 10:46 UTC, ckeiner commented on src/test/java/showcase/neodymium/tests/slider/SliderTest.java
> +        // pause between movements: 3000ms
Order the comments as the method expects them to come. This makes things more clear. Also fix it for the rest please.

2020-05-22 10:46 UTC, ckeiner commented on src/test/java/showcase/neodymium/tests/slider/SliderTest.java
> +        SelenideAddons.dragAndDropUntilCondition($(".balSlider a[role=slider]"), $(".balSlider a[role=slider]"), 40, 0, 3000, 5,
`".balSlider a[role=slider]"` is often used here and in the following code. It should help extracting it to a member variable. Then reuse it.

2020-05-22 10:46 UTC, ckeiner commented on src/test/java/showcase/neodymium/tests/slider/SliderTest.java
> +        SelenideAddons.dragAndDropUntilCondition($("#equalizer .k-slider-vertical:first-child a"), $("#equalizer .k-slider-vertical:first-child a"), 0, -10,
`"#equalizer .k-slider-vertical:first-child a"` is often used here and in the following code. It should help extracting it to a member variable. Then reuse it.

2020-05-22 10:46 UTC, ckeiner commented on src/test/java/showcase/neodymium/tests/slider/SliderTest.java
> +}
```suggestion
}

```
Add a new line to the end of the file.

2020-06-02 10:04 UTC, ckeiner reviewed
`elementToCheck` is always the same as `elementToMove`. Why do you need to allocate it? Can't I just use the same element twice?

2020-06-02 10:04 UTC, ckeiner commented on src/test/java/showcase/neodymium/tests/slider/SliderTest.java
> +    // move the slider to the right
The `@Description` already tells us what the test case does. Hence, you should rather place this above your comment chain on `SelenideAddons.dragAndDropUntilCondition`.

2020-06-02 10:04 UTC, ckeiner commented on src/test/java/showcase/neodymium/tests/slider/SliderTest.java
> +    // move the slider to the left
The `@Description` already tells us what the test case does. Hence, you should rather place this above your comment chain on `SelenideAddons.dragAndDropUntilCondition`.

2020-06-02 10:04 UTC, ckeiner commented on src/test/java/showcase/neodymium/tests/slider/SliderTest.java
> +    // move the slider to the top
The `@Description` already tells us what the test case does. Hence, you should rather place this above your comment chain on `SelenideAddons.dragAndDropUntilCondition`.

2020-06-02 10:04 UTC, ckeiner commented on src/test/java/showcase/neodymium/tests/slider/SliderTest.java
> +    // move the slider to the bottom
The `@Description` already tells us what the test case does. Hence, you should rather place this above your comment chain on `SelenideAddons.dragAndDropUntilCondition`.

2020-06-02 10:04 UTC, ckeiner commented on src/test/java/showcase/neodymium/tests/slider/SliderTest.java
> +    // move the slider to the top
This might just be me, but `top` sounds like you move it all the way to the top, so "move the slider upwards" might sound better.

2020-06-02 10:04 UTC, ckeiner commented on src/test/java/showcase/neodymium/tests/slider/SliderTest.java
> +    // move the slider to the bottom
This might just be me, but `bottom` sounds like you move it all the way to the bottom, so "move the slider downwards" might sound better.

2020-06-02 10:04 UTC, ckeiner commented on src/test/java/showcase/neodymium/tests/slider/SliderTest.java
> +}
Please add a new line.

2020-06-02 10:04 UTC, ckeiner commented on README.md
> +The `showcase.neodymium.tests.slider` package contains the use cases to drag and drop a web slider into different directions e.g. horizontal and vertical.
```suggestion
The `showcase.neodymium.tests.slider` package contains use cases to drag and drop a web slider into different directions i.e. horizontal and vertical.
```

2020-06-02 10:04 UTC, ckeiner commented on README.md
> -
Add the removed new line in again.

2020-06-02 10:04 UTC, ckeiner commented on README.md
> +## 3. Web slider
```suggestion

## 3. Web slider 
```

New line for better separation.

2020-06-04 09:30 UTC, jseng92 commented on src/test/java/showcase/neodymium/tests/slider/SliderTest.java
> +    // move the slider to the right
its ok like this

2020-06-05 08:09 UTC, ckeiner commented
Either comment on my suggestions/review on why you do not think that it is helpful or do it.

2020-07-01 13:01 UTC, merged