Showcase DataUtils #30 / out of the box approaches
Xceptance/neodymium-showcase pull request #31
Opened 2021-02-11 14:30 UTC by rkl-xc

2021-03-18 14:07 UTC, occupant23 commented
Decide together with @ufjena to not show case this approach further since it has no major advantages over using data objects and would need to introduce, document and maintain new code.
Furthermore, the flat data structure can become unhandy when maintaining big data sets.

2021-03-23 13:17 UTC, occupant23 requested changes
Please see the comments

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataObjectsTest.java
> + * This is a show case to explain how to deal with test data using the Neodymium built in features.<br>
better 'built-in' instead of 'built in'

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataObjectsTest.java
> + * In this case the test data are converted from a JSON file into java POJOs HomePageTestData and ServiceTile.<br>
typo: 'Java'

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataObjectsTest.java
> +    // in this case no @DataSet annotation is necessary because all test cases are to be executed
better: by default all available data sets will be executed, so there is no need to call them explicitly via the @DataSet annotation

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataObjectsTest.java
> +    @Description(value = "Get test data using java Pojo")
typo: Java

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataObjectsTest.java
> +        // check for Message and Comment
typos: message and comment

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataObjectsTest.java
> +        // check for serviceTiles on the page
typo service tiles

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataObjectsTest.java
> +        Iterator<ServiceTile> testDataServiceTiles = testDataHomePage.getServiceTiles().iterator();
Please use the following structure to iterate the list
```
        for (ServiceTile serviceTile : testDataHomePage.getServiceTiles())
        {
            
        }
```

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataSetAnnotationTest.java
> + * This is a show case to explain how to deal with test data using the Neodymium built in features.<br>
typo built-in

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataSetAnnotationTest.java
> +    @SuppressDataSets
needs to be above the class if it should be effective for the whole class other wise it effects only the function below

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataSetAnnotationTest.java
> +    // overrides the class level @SuppressDataSets to run with the first data set
overrides the class level @SuppressDataSets to run only the first data set

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataSetAnnotationTest.java
> +    // overrides the class level @SuppressDataSets to run with all data sets
overrides the class level @SuppressDataSets to run all data sets

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataUtilsTest.java
> +        // check Message and Comment
typo:  message and comment

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaJsonPathTest.java
> + * Therefore it is specified with the @DataFile annotation.<br>
replace 'with' with 'using'

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaJsonPathTest.java
> +        // check for Message and Comment
typo: message and comment

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/dataobjects/HomePageTestData.java
> +
remove newline

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/dataobjects/HomePageTestData.java
> +
add a simple toString method for the data object so it's easier to display the objects content

2021-03-23 13:17 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/dataobjects/ServiceTile.java
> +
add a simple toString method for the data object so it's easier to display the objects content

2021-03-23 13:17 UTC, occupant23 commented on src/test/resources/showcase/neodymium/tests/data/AccessDataViaDataObjectsTest.json
> +		"testId": "en/JSON test data access using java Pojo",
typo: Java

2021-03-23 13:17 UTC, occupant23 commented on src/test/resources/showcase/neodymium/tests/data/AccessDataViaDataObjectsTest.json
> +		"testId": "de/JSON test data access using java Pojo",
typo: Java

2021-03-23 13:17 UTC, occupant23 commented on src/test/resources/showcase/neodymium/tests/data/AccessDataViaDataObjectsTest.json
> +]
add newline at EOF

2021-03-23 13:17 UTC, occupant23 commented on src/test/resources/showcase/neodymium/tests/data/AccessDataViaDataSetAnnotationTest.json
> +]
add newline at EOF

2021-03-23 13:17 UTC, occupant23 commented on src/test/resources/showcase/neodymium/tests/data/AccessDataViaDataUtilsTest.xml
> +</datafile>
add newline at EOF

2021-03-23 13:17 UTC, occupant23 commented on src/test/resources/showcase/neodymium/tests/data/DataFilePriotityTest.json
> +]
add newline at EOF

2021-03-23 13:17 UTC, occupant23 commented on src/test/resources/showcase/neodymium/tests/data/TestDataFileWithDifferentName.json
> +]
add newline at EOF

2021-03-26 10:37 UTC, occupant23 requested changes
please take care of the comments

2021-03-26 10:37 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataObjectsTest.java
> +            // next serviceTile is expected at next position
comment not needed anymore

2021-03-26 10:37 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataObjectsTest.java
> +            System.out.println(serviceTile);
sysout not needed for this test case.

2021-03-26 10:37 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataSetAnnotationTest.java
> +        // // check headline and description
remove one of the '//'

2021-03-26 10:37 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaDataUtilsTest.java
> + * This is a show case to explain how to deal with test data using the Neodymium built in features.<br>
typo: built-in

2021-03-26 10:37 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/AccessDataViaJsonPathTest.java
> +// force Neodymium to use a different than standard named data file under src/test/ressources/
use tell instead of force sounds less hard

2021-03-26 10:37 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/dataobjects/HomePageTestData.java
> +
add a short comment why we recommend to overrride the toString method

2021-03-26 10:37 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/data/dataobjects/ServiceTile.java
> +
add a short comment why we recommend to overrride the toString method

2021-03-29 12:36 UTC, occupant23 approved these changes

2021-03-29 12:39 UTC, merged

2021-04-08 15:35 UTC, georgkunze commented
@occupant23 Rechecked! It think it is Ok as it is.