#37 showcase nextboolean
Xceptance/neodymium-showcase pull request #38
Opened 2021-04-14 09:36 UTC by ufjena

2021-04-14 09:37 UTC, ufjena commented
@georgkunze please review the RandomProbabilityTest class.
Please also have a look at the Javadoc in all random test classes.

2021-04-14 10:51 UTC, georgkunze commented
@ufjena the logmessages are missleading and are not in all cases represent the actual percentage entered/observable. Could you look into that?

2021-04-16 10:24 UTC, occupant23 requested changes
please see the comments

2021-04-16 10:24 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/pdf/PdfTextContentCheckTest.java
> - * <br>
Please add this as information to documentation, that the dependency is required but already prepared by us.

2021-04-16 10:24 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/random/FixedRandomTest.java
> + * <li>A value for neodymium.context.random.initialValue must be set.</li>
you can already state the expected value in the documentation  

`... must be set to 123456789.`

2021-04-16 10:24 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/random/RandomProbabilityTest.java
> +    private static Logger logger = LogManager.getLogger(LoggingFirstTest.class);
better 
`private static final Logger LOGGER`

2021-04-16 10:24 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/random/RandomProbabilityTest.java
> +        // this means that true and false are returned in equal parts
this mean that true and false should be returned approximately equally probable.

2021-04-16 10:24 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/random/RandomProbabilityTest.java
> +        // this means that true is returned at 80% and false at 20%
this means the ratio of true and false should be approximately about 80 to 20 in favor of true.

2021-04-19 09:49 UTC, occupant23 requested changes

2021-04-19 09:49 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/logging/LoggingFirstTest.java
> + * Then it will look for log4j2.properties on the classpath. The same goes for yaml, json and xml files.<br>
The same mechanism applies for other file formats like yaml, json and xml.

2021-04-19 09:49 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/pdf/PdfTextContentCheckTest.java
> - * <br>
@ufjena this hasn't been covered yet.

2021-04-19 09:49 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/random/RandomProbabilityTest.java
> +        // this mean that true and false should be returned approximately equally probable
this means that true and false should be returned approximately equally

2021-04-23 08:40 UTC, occupant23 requested changes
On last thing :-)

2021-04-23 08:40 UTC, occupant23 commented on src/test/java/showcase/neodymium/tests/pdf/PdfTextContentCheckTest.java
> + * In order to be able to use pdfbox, a dependency entry <i>org.apache.pdfbox</i> is required in the <i>pom.xml but
In order to use PDFbox you would need to add a dependency for <i>org.apache.pdfbox</i> to your project's <i>pom.xml</i> file. For this show case project we already prepared this and you can have a look if you're struggling with the setup.<br>

2021-04-23 09:43 UTC, occupant23 approved these changes

2021-04-23 09:43 UTC, merged